name: Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Name"
        type: string
        required: true
jobs:
  Testjobs:
    runs-on: ubuntu-latest

    steps:
      - name: Name
        run: echo "Hi ${{inputs.name}}"

    
